server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/corn?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
